name: CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  run-curl:
    runs-on: ubuntu-latest

    steps:
      # see https://pkg.go.dev/about#adding-a-package
      - name: Update pkg.go.dev
        run: |
          ESCAPED_MODULE=echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'
          curl https://proxy.golang.org/github.com/$ESCAPED_MODULE/@v/$GITHUB_REF_NAME.info